/**
 * The committed palette.css and the module it comes from have to agree.
 *
 * The stylesheet is generated but checked in, so the repository reads without
 * running a build and a palette change shows up as colours moving. The cost of
 * that choice is a copy that can go stale -- someone edits src/shared/theme.ts,
 * commits, and the app keeps drawing the old colours because Vite bundled the
 * old file. This is the guard, and it is the same shape as the drift it
 * replaces: the site carried the app's palette by hand and was seven values
 * behind before anyone noticed.
 */

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

import {
  paletteCss,
  siteCss,
  TARGET,
  SITE,
  COMPILED,
  SHADOW_PREFIX,
  SITE_MAP,
} from "#tools/build-theme.js";

/* The module as the generator sees it: the compiled one, not the source. */
const theme = require(COMPILED);

test("the committed palette.css is what the generator would write", () => {
  const committed = fs.readFileSync(TARGET, "utf8");
  assert.equal(
    committed,
    paletteCss(theme),
    `${path.basename(TARGET)} is stale -- run \`node tools/build-theme.js\``,
  );
});

test("every role reaches the stylesheet, in both themes", () => {
  const css = paletteCss(theme);
  const light = css.slice(0, css.indexOf(':root[data-theme="dark"]'));
  const dark = css.slice(css.indexOf(':root[data-theme="dark"]'));
  for (const [role, value] of Object.entries(theme.PALETTE.light)) {
    assert.match(light, new RegExp(`--${role}: ${value};`), `light ${role}`);
  }
  for (const [role, value] of Object.entries(theme.PALETTE.dark)) {
    assert.match(dark, new RegExp(`--${role}: ${value};`), `dark ${role}`);
  }
});

test("shadows are emitted under their own prefix", () => {
  // Not --shadow-*: Tailwind's @theme owns that namespace and writes its values
  // to a bare :root, so the two would collide and source order would decide
  // which theme's shadow won.
  const css = paletteCss(theme);
  for (const role of Object.keys(theme.SHADOW.light)) {
    assert.ok(
      css.includes(`${SHADOW_PREFIX}${role}:`),
      `${SHADOW_PREFIX}${role} is missing`,
    );
    assert.ok(
      !css.includes(`--shadow-${role}:`),
      `--shadow-${role} would collide with @theme`,
    );
  }
});

test("the generated file says it is generated", () => {
  // Someone will open it and start editing otherwise, and their change will
  // survive exactly until the next build.
  const committed = fs.readFileSync(TARGET, "utf8");
  assert.match(committed, /Generated by tools\/build-theme\.js/);
  assert.match(committed, /Do not edit/);
});

/* ------------------------------------------------------------------- the site */

test("the committed site stylesheet carries the current palette", () => {
  // Generated between markers rather than into a file of its own: the site
  // keeps one stylesheet on purpose, because a page a store links to should
  // render on anything, and a second request is a second thing to go wrong.
  const committed = fs.readFileSync(SITE, "utf8");
  assert.ok(
    committed.includes(siteCss(theme)),
    "site/style.css is stale -- run `node tools/build-theme.js`",
  );
});

test("the site's markers are both still there", () => {
  // The generator refuses to guess where the region is, so losing a marker has
  // to fail loudly rather than append a second palette to the end of the file.
  const committed = fs.readFileSync(SITE, "utf8");
  assert.match(committed, /\/\* palette:start/);
  assert.match(committed, /\/\* palette:end \*\//);
});

test("every site name maps to a role that exists", () => {
  // The site's names predate the app's vocabulary, so the mapping is the only
  // thing holding them together. A typo here would emit `undefined`.
  for (const [name, role] of Object.entries(SITE_MAP) as [string, string][]) {
    assert.ok(theme.PALETTE.light[role], `${name} points at a missing ${role}`);
    assert.ok(theme.PALETTE.dark[role], `${name} points at a missing ${role}`);
  }
  assert.ok(!siteCss(theme).includes("undefined"));
});
