/**
 * The committed palette.css and the module it comes from have to agree.
 *
 * The stylesheet is generated but checked in, so the repository reads without
 * running a build and a palette change shows up as colours moving. The cost of
 * that choice is a copy that can go stale -- someone edits src/shared/theme.ts,
 * commits, and the app keeps drawing the old colours because Vite bundled the
 * old file. This is the guard, and it is the same shape as the drift it
 * replaces: the site carried the app's palette by hand and was seven values
 * behind before anyone noticed.
 */

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

import { paletteCss, TARGET, COMPILED, SHADOW_PREFIX } from "#tools/build-theme.js";

/* The module as the generator sees it: the compiled one, not the source. */
const theme = require(COMPILED);

test("the committed palette.css is what the generator would write", () => {
  const committed = fs.readFileSync(TARGET, "utf8");
  assert.equal(
    committed,
    paletteCss(theme),
    `${path.basename(TARGET)} is stale -- run \`node tools/build-theme.js\``,
  );
});

test("every role reaches the stylesheet, in both themes", () => {
  const css = paletteCss(theme);
  const light = css.slice(0, css.indexOf(':root[data-theme="dark"]'));
  const dark = css.slice(css.indexOf(':root[data-theme="dark"]'));
  for (const [role, value] of Object.entries(theme.PALETTE.light)) {
    assert.match(light, new RegExp(`--${role}: ${value};`), `light ${role}`);
  }
  for (const [role, value] of Object.entries(theme.PALETTE.dark)) {
    assert.match(dark, new RegExp(`--${role}: ${value};`), `dark ${role}`);
  }
});

test("shadows are emitted under their own prefix", () => {
  // Not --shadow-*: Tailwind's @theme owns that namespace and writes its values
  // to a bare :root, so the two would collide and source order would decide
  // which theme's shadow won.
  const css = paletteCss(theme);
  for (const role of Object.keys(theme.SHADOW.light)) {
    assert.ok(
      css.includes(`${SHADOW_PREFIX}${role}:`),
      `${SHADOW_PREFIX}${role} is missing`,
    );
    assert.ok(
      !css.includes(`--shadow-${role}:`),
      `--shadow-${role} would collide with @theme`,
    );
  }
});

test("the generated file says it is generated", () => {
  // Someone will open it and start editing otherwise, and their change will
  // survive exactly until the next build.
  const committed = fs.readFileSync(TARGET, "utf8");
  assert.match(committed, /Generated by tools\/build-theme\.js/);
  assert.match(committed, /Do not edit/);
});
