/**
 * Turn src/shared/theme.ts into the stylesheet the renderer reads.
 *
 * The palette has to exist as data -- the export document, the website and
 * anything mobile cannot read a stylesheet -- and it has to exist as CSS
 * variables, because that is how a theme switches at runtime. Writing both by
 * hand is how the site ended up seven values away from the app before #91. So
 * one of them is generated, and this is it.
 *
 * The output is committed. That is deliberate: the repository should be
 * readable without running a build, and a diff on the palette should show the
 * colours changing rather than a build step changing. `tools/test/` asserts the
 * committed copy matches what this would write, so a stale one is a red test
 * rather than a mystery.
 *
 * It reads out/shared/theme.js rather than the .ts, so `npm run build` has to
 * have compiled shared/ first -- tools/build.js calls this between the
 * compilers and Vite for exactly that reason. Run alone before a build has ever
 * happened, it says so and leaves the committed file alone.
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const COMPILED = path.join(ROOT, "out", "shared", "theme.js");
const TARGET = path.join(ROOT, "src", "renderer", "styles", "palette.css");
const SITE = path.join(ROOT, "site", "style.css");

/**
 * The site's names, which predate the app's vocabulary, mapped to the roles.
 *
 * `--accent-link` used to be the accent darkened to 74%, because a terracotta
 * link on cream measured 2.69:1. It does not need darkening now and does not
 * get a hue either: with an ink accent a link is body-coloured and underlined,
 * which is what WCAG asks for anyway -- colour is never the only signal.
 */
const SITE_MAP = {
  "--bg": "bg",
  "--fg": "text",
  "--muted": "muted",
  "--line": "line",
  "--card": "panel",
  "--accent": "accent",
  "--code-bg": "panel-2",
  "--accent-link": "accent",
};
const SITE_START = "/* palette:start";
const SITE_END = "/* palette:end */";

/**
 * Colours keep the names the stylesheets already use, so `--color-panel:
 * var(--panel)` in index.css goes on working. The shadows cannot: Tailwind's
 * `@theme` owns the `--shadow-*` namespace and writes its own values to a bare
 * `:root`, which would collide. `--sh-*` is the raw themed value; `@theme`
 * points the utility names at it.
 */
const SHADOW_PREFIX = "--sh-";

const HEADER = `/* Generated by tools/build-theme.js from src/shared/theme.ts.
   Do not edit: the next build overwrites it, and tools/test/build-theme.test.ts
   fails if this file and the module disagree.

   Two layers live here. The ramp is fourteen greys and the only literal colours
   in the neutral system; these declarations are the second layer, where each
   theme says which step plays which part. Change a value in the module, not
   here. */
`;

function block(selector, entries) {
  const body = entries.map(([name, value]) => `  ${name}: ${value};`).join("\n");
  return `${selector} {\n${body}\n}\n`;
}

/** The stylesheet, as a string, from the palette module. */
function paletteCss(theme) {
  const { PALETTE, SHADOW, THEMES } = theme;
  const entriesFor = (name) => [
    ...Object.entries(PALETTE[name]),
    ...Object.entries(SHADOW[name]).map(([role, value]) => [
      `${SHADOW_PREFIX}${role}`,
      value,
    ]),
  ].map(([key, value]) => [key.startsWith("--") ? key : `--${key}`, value]);

  // Light doubles as the default, the way base.css declared it: a window with
  // no stored choice is a light one.
  const parts = [
    block(':root,\n:root[data-theme="light"]', entriesFor("light")),
    block(':root[data-theme="dark"]', entriesFor("dark")),
  ];
  void THEMES;
  return `${HEADER}\n${parts.join("\n")}`;
}

/**
 * Write it, and answer whether anything moved.
 *
 * Returning "unchanged" rather than always writing keeps `npm run build`
 * from touching a file's mtime for no reason, which matters on the watch path:
 * Vite is watching this directory.
 */
function writeTheme({ quiet = false } = {}) {
  if (!fs.existsSync(COMPILED)) {
    if (!quiet) {
      console.log(
        "theme: out/shared/theme.js is not built yet, keeping the committed palette.css",
      );
    }
    return "skipped";
  }
  // require() of an ES module, which Node has been able to do since 22.12 and
  // which the rest of out/shared already relies on.
  const css = paletteCss(require(COMPILED));
  const before = fs.existsSync(TARGET) ? fs.readFileSync(TARGET, "utf8") : null;
  if (before === css) return "unchanged";
  fs.writeFileSync(TARGET, css);
  if (!quiet) console.log(`theme: wrote ${path.relative(ROOT, TARGET)}`);
  return before === null ? "created" : "changed";
}

/** The site's two blocks, in the site's own names. */
function siteCss(theme) {
  const rows = (name, indent) =>
    Object.entries(SITE_MAP)
      .map(([css, role]) => `${indent}${css}: ${theme.PALETTE[name][role]};`)
      .join("\n");
  return [
    ":root {",
    rows("light", "  "),
    "}",
    "@media (prefers-color-scheme: dark) {",
    "  :root {",
    rows("dark", "    "),
    "  }",
    "}",
  ].join("\n");
}

/** Replace what sits between the markers, and answer whether it moved. */
function writeSite({ quiet = false } = {}) {
  if (!fs.existsSync(COMPILED)) return "skipped";
  const before = fs.readFileSync(SITE, "utf8");
  const open = before.indexOf(SITE_START);
  const close = before.indexOf(SITE_END);
  if (open === -1 || close === -1) {
    throw new Error(`${SITE} has lost its palette markers`);
  }
  const head = before.slice(0, before.indexOf("*/", open) + 3);
  const after = [head, siteCss(require(COMPILED)), before.slice(close)].join(
    "\n",
  );
  if (after === before) return "unchanged";
  fs.writeFileSync(SITE, after);
  if (!quiet) console.log(`theme: wrote ${path.relative(ROOT, SITE)}`);
  return "changed";
}

module.exports = {
  writeTheme,
  writeSite,
  paletteCss,
  siteCss,
  TARGET,
  SITE,
  COMPILED,
  SHADOW_PREFIX,
  SITE_MAP,
};

if (require.main === module) {
  writeTheme();
  writeSite();
}
